id: P008232
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03789
  title: འདས་ལོག་དཀར་ཆག་ཐར་པའི་ལམ་སྟོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    d0db12356521416caa1f594bc7689150:
      image_group_id: I00KG03820
      title: ''
      volume_number: 1
      total_pages: 66
