id: P008232
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:09:27.989814
source_metadata:
  id: bdr:W00KG03789
  title: འདས་ལོག་དཀར་ཆག་ཐར་པའི་ལམ་སྟོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    d0db12356521416caa1f594bc7689150:
      image_group_id: I00KG03820
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
