id: IDEE83D81
legacy_id: P008232
ocr_import_info:
  bdrc_scan_id: W00KG03789
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T23:10:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:10:35.725695+00:00'
last_modified: 2022-08-29 20:10:50.592948
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03789
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03789
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདས་ལོག་དཀར་ཆག་ཐར་པའི་ལམ་སྟོན་གསལ་བའི་སྒྲོན་མེ།
  author: སྟག་བླ་དཀོན་མཆོག་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9474455880378405
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG03820:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03820
      total_pages: 66
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03820.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9474455880378405
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
